This is to handle an issue we ran into when we tried compiling and     running with the header-only HIP on CUDA install on JLSE.
    If we tried running without any changes, what we saw was:

    ```
    $ python2 ./ert --verbose=3 Config/config.hip-fp64.v100.jlse.anl.gov.01

    Reading configuration from 'Config/config.hip-fp64.v100.jlse.anl.gov.01'...
      Using existing results directory, Results.hip.v100.fp64.01...
        Using existing run directory, Results.hip.v100.fp64.01/Run.001...

    FLOP count 1...

      Building ERT core code...
        hipcc -O3 -I./Kernels -DERT_FLOP=1 -DERT_ALIGN=32 -DERT_MEMORY_MAX=1073741824 -DERT_WORKING_SET_MIN=128 -DERT_TRIALS_MIN=1 -DERT_WSS_MULT=1.1 -DERT_GPU -arch=sm_70 -DERT_HIP -DERT_FP64 -c ./Drivers/driver1.cxx -o Results.hip.v100.fp64.01/Run.001/FLOPS.001/driver1.o
    Use of uninitialized value $HIP_COMPILER in string ne at /soft/compilers/HIP/20200819/bin/hipcc line 657.
    /soft/compilers/HIP/20200819/include/hip/nvcc_detail/hip_runtime_api.h(179): error: identifier "hipEvent_t" is undefined

    /soft/compilers/HIP/20200819/include/hip/nvcc_detail/hip_runtime_api.h(480): error: return value type does not match the function type

    /soft/compilers/HIP/20200819/include/hip/nvcc_detail/hip_runtime_api.h(645): error: return value type does not match the function type

    /soft/compilers/HIP/20200819/include/hip/nvcc_detail/hip_runtime_api.h(647): error: return value type does not match the function type

    /soft/compilers/HIP/20200819/include/hip/nvcc_detail/hip_runtime_api.h(719): error: argument of type "hipError_t" is incompatible with parameter of type "cudaError_t"
    ```

    when I looked into "hip_runtime_api.h", I see basically
    ```
    typedef cudaEvent_t hipEvent_t;
    ```

    ERT’s HIP port is

    ```
	#define cudaEvent_t hipEvent_t
    ```

    the main file has

    ```
    #include “driver.h” [#defines as above]
    #include "kernel1.h" [includes hip_runtime_api.h]
    ```

    So since the headers are in this order, hip_runtime_api.h is affected by the ERT port’s #defines,
    we end up with “typedef hipEvent_t hipEvent_t“, and see the errors above.

    We can get around by switching the order:

    ```
    #include "kernel1.h" [includes hip_runtime_api.h]
    #include “driver.h” [#defines as above]
    ```

    but this caused issues for uint64_t for CUDA runs:

    ```
    $ python2 ./ert --verbose=3 Config/config.cuda-fp64.v100.jlse.anl.gov.01

    Reading configuration from 'Config/config.cuda-fp64.v100.jlse.anl.gov.01'...
      Making new results directory, Results.corigpu-cuda-fp64.01...
        Making new run directory, 'Results.corigpu-cuda-fp64.01/Run.001'...
        mkdir Results.corigpu-cuda-fp64.01/Run.001
        cp Config/config.cuda-fp64.v100.jlse.anl.gov.01 Results.corigpu-cuda-fp64.01/Run.001/config.ert

    FLOP count 1...
        mkdir Results.corigpu-cuda-fp64.01/Run.001/FLOPS.001

      Building ERT core code...
        nvcc -O3 -I./Kernels -DERT_FLOP=1 -DERT_ALIGN=32 -DERT_MEMORY_MAX=1073741824 -DERT_WORKING_SET_MIN=128 -DERT_TRIALS_MIN=1 -DERT_WSS_MULT=1.1 -DERT_GPU -x cu -arch=sm_70 -DERT_FP64 -c ./Drivers/driver1.cxx -\
    o Results.corigpu-cuda-fp64.01/Run.001/FLOPS.001/driver1.o
    ./Kernels/kernel1.h(33): error: identifier "uint64_t" is undefined

    ./Kernels/kernel1.h(48): error: identifier "uint64_t" is undefined
    ```

    To avoid this, I moved inttypes.h into kernel1.h
    so it's still before driver.h, too. This avoids the error above.